# Generated by Django 5.0 on 2023-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_registry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='employed_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='role',
        ),
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
